on:
  workflow_call:
    inputs:
      is-external-pr:
        description: 'Whether this is an external PR from a fork'
        type: boolean
        required: false
        default: false
      pr-head-sha:
        description: 'PR head SHA for external PRs'
        type: string
        required: false
        default: ''
      pr-head-repo:
        description: 'PR head repository for external PRs'
        type: string
        required: false
        default: ''

jobs:
  test:
    runs-on: [self-hosted, x64]
    environment: ${{ inputs.is-external-pr && 'external-pr-approval' || null }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.is-external-pr && inputs.pr-head-sha || github.sha }}
          repository: ${{ inputs.is-external-pr && inputs.pr-head-repo || github.repository }}

      - name: PR Type Notice
        run: |
          if [ "${{ inputs.is-external-pr }}" = "true" ]; then
            echo "::notice::External PR detected - using stable workflows from main branch"
            echo "::notice::Testing code from: ${{ inputs.pr-head-repo }}@${{ inputs.pr-head-sha }}"
          else
            echo "::notice::Internal PR detected - using workflows from PR branch"
          fi

      - name: Install dependencies
        continue-on-error: true # JLink install may fail
        run: |
          if [ ! -f "`which JLinkExe`" ]; then
            echo "Installing JLink tools..."
            sudo apt-get update
            sudo apt-get install -y udev
            wget -q --post-data 'accept_license_agreement=accepted&non_emb_ctr=confirmed&submit=Download+software' https://www.segger.com/downloads/jlink/JLink_Linux_V856a_x86_64.deb
            sudo apt -qq update
            sudo apt -y install ./JLink_Linux_V856a_x86_64.deb &>/dev/null
          fi

          if [ ! -f "`which nrfjprog`" ]; then
            echo "Installing Nordic command line tools..."
            wget -q https://nsscprodmedia.blob.core.windows.net/prod/software-and-other-downloads/desktop-software/nrf-command-line-tools/sw/versions-10-x-x/10-24-2/nrf-command-line-tools_10.24.2_amd64.deb
            sudo apt -y install ./nrf-command-line-tools_10.24.2_amd64.deb
            export PATH=$PATH:/opt
          fi

          if [ ! -f "`which nrfutil`" ]; then
            echo "Installing nrfutil udev rules..."
            sudo apt install -y libusb-1.0-0
            wget -q https://github.com/NordicSemiconductor/nrf-udev/releases/download/v1.0.1/nrf-udev_1.0.1-all.deb
            sudo dpkg -i nrf-udev_1.0.1-all.deb

            echo "Installing nrfutil..."
            wget -q https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o nrfutil
            sudo mv nrfutil /opt/nrfutil
            sudo chmod +x /opt/nrfutil

            echo "nrfutil self-upgrade..."
            /opt/nrfutil self-upgrade
            /opt/nrfutil install device
            export PATH=$PATH:/opt
          fi

          sudo apt-get install -y bluez
          sudo apt-get install -y xvfb
          sudo apt-get install -y imagemagick
          sudo apt-get install -y python-is-python3
          sudo apt-get install -y python3-pip
          sudo apt-get install -y python3-venv

          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r app/pytest/requirements.txt

          # Needed for running native_sim application in tests
          sudo apt-get install -y build-essential
          sudo apt-get install -y libsdl2-dev
          sudo usermod -aG bluetooth $USER
          sudo setcap cap_net_admin=eip $(which btmgmt)

          # For UART
          sudo usermod -aG dialout $USER

      - name: 'Download image'
        uses: actions/download-artifact@v4
        with:
          name: watchdk@1_nrf5340_cpuapp_debug
          path: app/pytest/

      - name: 'Download image'
        uses: actions/download-artifact@v4
        with:
          name: zswatch_legacy@5_nrf5340_cpuapp_debug
          path: app/pytest/

      - name: 'Download image'
        uses: actions/download-artifact@v4
        with:
          name: native_sim_native_64_debug
          path: app/pytest/

      - name: Display structure of downloaded files
        run: |
          ls
          ls app/pytest

      - name: Test with pytest
        id: pytest_run
        run: |
          set +e
          source .venv/bin/activate
          cd app/pytest

          # Make sure bt hci adapter is on.
          sudo btmgmt --index 0 power off
          sudo btmgmt --index 0 power on

          pytest \
            --junitxml=report_target.xml -v \
            -m 'not linux_only' \
            --html=report_target.html \
            --self-contained-html
          pytest \
            --board=native_sim \
            -m 'linux_only' --board=native_sim \
            --junitxml=report_linux.xml -v \
            --html=report_linux.html \
            --self-contained-html

      - name: Upload test reports
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/pytest/report_*.xml
            app/pytest/report_*.html
            app/pytest/power_results.json

      - name: Annotate test failures in PR
        if: success() || failure()
        uses: mikepenz/action-junit-report@v5
        continue-on-error: true # Ensure this step never fails the workflow
        with:
          report_paths: 'app/pytest/report_*.xml'
          include_passed: true
          detailed_summary: true
          job_summary: true
          comment: true
          updateComment: true
          annotate_notice: true
          annotations_limit: 50
          fail_on_failure: false # Until test setup is stable, let it fail gracefully
          fail_on_parse_error: false # Don't fail on XML parsing errors
          require_tests: false # Don't require tests to be found

      - name: Create/Update Power Consumption Comment
        if: success() || failure()
        continue-on-error: true
        run: |
          source .venv/bin/activate
          cd app/pytest
          if [ -f "power_results.json" ]; then
            echo "Generating power consumption comment..."
            python power_logger.py > power_comment.md
          else
            echo "## ⚡ Power Consumption" > power_comment.md
            echo "" >> power_comment.md
            echo "❌ No power consumption tests were run in this build." >> power_comment.md
          fi

      - name: Find existing power consumption comment
        if: success() || failure()
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '⚡ Power Consumption'

      - name: Create or update power consumption comment
        if: success() || failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: app/pytest/power_comment.md
          edit-mode: replace
